version: '3.8'

services:
  selenium-firefox:
    image: selenium/standalone-firefox:latest
    container_name: selenium-firefox
    ports:
      - "4444:4444"
    restart: always
    volumes:
      - "C:\\Users\\Revio\\OneDrive\\Área de Trabalho\\REVIO\\Códigos provisórios\\api_bd_falso\\TJMG:/home/seluser/Downloads"
    shm_size: 2g
    networks:
      - app_network

  app:
    image: bot_retroativo_api:latest
    container_name: download_retroativo
    depends_on:
      - selenium-firefox
    environment:
      - SELENIUM_HOST=selenium-firefox
    ports:
      - "8000:8000"
    volumes:
      - /TJMG
    command: ["/opt/venv/bin/uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]
    runtime: nvidia
    networks:
      - app_network

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: luca69892
      MONGO_INITDB_ROOT_PASSWORD: SeitiRevio!
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
